### PR TITLE
fix button

### PR DESCRIPTION
**Pull request by kamila-wilczynska**
fix button css

image

### CODE REVIEW

**Review by BlueElyas — APPROVED** [review]

**Review by Sebbybobbler — APPROVED** [review]

**Review by NicoClack — APPROVED** [review]

**Comment by NicoClack** [comment]
@cnrdgrgry You snooze you lose 😆

**Comment by cnrdgrgry** [comment]
Wtf?! 😬😂

**Comment by cnrdgrgry** [comment]
I was on the beers already.

Skool'z out for Summer!

**Comment by NicoClack** [comment]
@cnrdgrgry We accidentally assigned you

**Pull request merged**
